# Generated by Django 4.1.1 on 2022-10-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceApp', '0006_alter_wishlistdb_performance_seq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momo', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('wishlist_id', models.ForeignKey(db_column='wishlist_id', on_delete=django.db.models.deletion.CASCADE, to='InterfaceApp.wishlistdb')),
            ],
        ),
    ]
